### ISSUE TITLE
当new Session的时候，是否可以增加跳过kerberos验证？

### ISSUE THREAD

**Issue by Nicoveu** [hligaty/haibaracp-spring-boot-starter#1]
Properties properties = new Properties();
//disable Kerberos
properties.put("PreferredAuthentications", "publickey,keyboard-interactive,password");
session.setConfig(properties);

**Comment by hligaty** [comment]
[disable Kerberos](https://github.com/hligaty/haibaracp-spring-boot-starter/commit/a7032d3d8d67efdc125bb35e7d316be8b05140ae#diff-39d1e32d061a5709c0fb59a26a46a7d91d967ab09da0632fcc0b951f90e43deb) 已提交，如果没有问题我将在明天发布到中央仓库。
