### ISSUE TITLE
是否可以加上自动的重试次数

### ISSUE THREAD

**Issue by dragontree101** [hligaty/haibaracp-spring-boot-starter#4]
有时候批量任务的时候网络不太好,网络链接会断掉(比如下载文件等操作的时候),是否可以加上自动的重试?

**Comment by hligaty** [comment]
网络不好的时候立即重试的意义不大，复杂的重试逻辑可以试试 spring retry

**Comment by dragontree101** [comment]
也是, 这个可能重试是需要业务层面进行考虑的, 和本项目的sftp+对象池的主要的功能并不太相关, 谢谢大佬了, 我把问题暂时关闭了
