### ISSUE TITLE
获取sftpClient长时间阻塞

### ISSUE THREAD

**Issue by caizy-2020** [hligaty/haibaracp-spring-boot-starter#6]
**引用的版本：**
```
<dependency>
    <groupId>io.github.hligaty</groupId>
    <artifactId>haibaracp-spring-boot-starter</artifactId>
    <version>1.2.3</version>
</dependency>
```

**本地的配置：**
```
sftp.pool.min-idle-per-key=1
sftp.pool.max-idle-per-key=8
sftp.pool.max-active-per-key=8
sftp.pool.max-active=8
sftp.pool.max-wait=-1
sftp.pool.test-on-borrow=true
sftp.pool.test-on-return=false
sftp.pool.test-while-idle=true
sftp.pool.time-between-eviction-runs=600000
sftp.pool.min-evictable-idle-time-millis=1800000
```

**问题点：**
1、根据打印出的日志定位到`io.github.hligaty.haibaracp.core.SftpTemplate#execute`方法中的`sftpClient = sftpPool.borrowObject(hostKey);`会偶发的阻塞10几分钟，
![image](https://github.com/hligaty/haibaracp-spring-boot-starter/assets/65394715/1411a1da-0851-4678-b123-203cc03ea8dc)

阻塞结束后好像会开始执行`org.apache.commons.pool2.impl.GenericKeyedObjectPool#create`方法，因为阻塞结束后打印的是
```
com.jcraft.jsch Connecting to 10.132.4.99 port 12322
com.jcraft.jsch Connection established
```
![image](https://github.com/hligaty/haibaracp-spring-boot-starter/assets/65394715/a8bbc7b3-b525-4bc8-bd28-cc31483caa3c)

2、本地`SftpTemplate`的代码版本是：https://github.com/hligaty/haibaracp-spring-boot-starter/blob/a9a4c2ea38c5e12dd500040574ec871e3ee5ec9b/src/main/java/io/github/hligaty/haibaracp/core/SftpTemplate.java
3、因为是偶发的，我们也尝试了很久但没有找到复现方式，同时也没有额外的报错日志
4、有初步怀疑过是因为`borrowObject`后未执行`sftpPool.returnObject`或者执行`sftpPool.returnObject`出错才导致`borrowObject`阻塞的，但是我们加入日志后并未发现这一点，因为每次的`borrowObject`都有其对应的`sftpPool.returnObject`立即且成功执行

**期望：**
1、请问有可能导致该问题的原因有哪些？
2、我们有什么更进一步的日志打印/方式可帮助获取更精准的错误日志用于排查？
3、是否可以通过同步最新的`io.github.hligaty.haibaracp.core.SftpTemplate`避免该问题？

**Comment by hligaty** [comment]
1. 原因可能有两种，第一种：默认的建立连接不会超时([参数 connectionTimeout](https://github.com/hligaty/haibaracp-spring-boot-starter/blob/2e67a098f6eda8990aea23bff3d986f619a89b31/src/main/java/io/github/hligaty/haibaracp/config/ClientProperties.java#L60))，这样就会出现阻塞了很久才建立成功，可以指定合适的连接超时时间避免，详见 #2 ；第二种：所有持有连接池连接的线程都在执行耗时较长的操作，又因为 sftp.pool.max-wait=-1 导致请求获取连接的线程无限等待，许久后耗时较长的操作执行完并释放连接，这样无限等待的线程就成功获取到了连接（日志显示连接是新建立的，也就是 sftp.pool.test-on-borrow=true 没有通过连接检测），可以指定合适的借出超时时间避免。我认为第一种可能性较大。
2. 针对第一种原因可以在 [session.connect(clientProperties.getConnectTimeout());](https://github.com/hligaty/haibaracp-spring-boot-starter/blob/1e1127d6b66a4090114d52fe18cfbaddc353fe39/src/main/java/io/github/hligaty/haibaracp/core/SftpClient.java#L40C8-L40C8) 的前后增加日志来确定；针对第二种可以在连接归还到连接池时打印日志，以此确定获取连接时连接池是否已满。
3. 最新的版本无法避免该问题，问题原因应该是参数不合适导致的。

**Comment by caizy-2020** [comment]
好的，我们先试下第一种方案。
应该不是第二种原因，因为上面问题点的第4、有打印日志测试过很多次，借出去的连接都是短时间内就归还了的。
谢谢！

**Comment by caizy-2020** [comment]
**阻塞问题还是会存在**

**引用的版本：**
```
<dependency>
    <groupId>io.github.hligaty</groupId>
    <artifactId>haibaracp-spring-boot-starter</artifactId>
    <version>1.2.3</version>
</dependency>
```
**修改后的本地的配置：**
SFTP连接池配置：
```
sftp.pool.min-idle-per-key=1
sftp.pool.max-idle-per-key=8
sftp.pool.max-active-per-key=8
sftp.pool.max-active=8
sftp.pool.max-wait=3000
sftp.pool.test-on-borrow=true
sftp.pool.test-on-return=false
sftp.pool.test-while-idle=true
sftp.pool.time-between-eviction-runs=600000
sftp.pool.min-evictable-idle-time-millis=1800000
```
SFTP主机配置：
```
sftp.hosts.A.host=x.x.x.29
sftp.hosts.A.port=22
sftp.hosts.A.username=xx
sftp.hosts.A.password=xx
sftp.hosts.A.connectTimeout=3000

sftp.hosts.B.host=x.x.x.25
sftp.hosts.B.port=22
sftp.hosts.B.username=xx
sftp.hosts.B.password=xx
sftp.hosts.B.connectTimeout=3000
```

**问题描述：**
1、确实发现有出现A主机连接超时的情况，部分日志：
```
Caused by: java.lang.IllegalStateException: failed to create sftp Client
	at io.github.hligaty.haibaracp.core.SftpClient.<init>(SftpClient.java:46)
	at io.github.hligaty.haibaracp.core.SftpPool$KeyedPooledClientFactory.create(SftpPool.java:125)
	at io.github.hligaty.haibaracp.core.SftpPool$KeyedPooledClientFactory.create(SftpPool.java:115)
	at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1073)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:348)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:271)
	at io.github.hligaty.haibaracp.core.SftpPool.borrowObject(SftpPool.java:37)
	... 107 common frames omitted
Caused by: com.jcraft.jsch.JSchException: timeout: socket is not established
	at com.jcraft.jsch.Util.createSocket(Util.java:394)
	at com.jcraft.jsch.Session.connect(Session.java:215)
	at io.github.hligaty.haibaracp.core.SftpClient.<init>(SftpClient.java:40)
	... 114 common frames omitted
```
2、设置了连接超时，A主机的连接应该不会长期占用才对，但连接A和B主机都会出现阻塞（未修改配置前也有该问题）
3、另外我们本次加入数据库连接池的日志打印，设置阻塞5分钟数据库连接就会断开并且定位具体阻塞的位置，部分日志：
```
ownerThread current state is RUNNABLE, current stackTrace
	at java.base@11/java.io.FileInputStream.open0(Native Method)
	at java.base@11/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base@11/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base@11/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at com.jcraft.jsch.Util.fromFile(Util.java:508)
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:540)
	at com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:40)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:406)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:366)
	at io.github.hligaty.haibaracp.core.SftpClient.<init>(SftpClient.java:32)
	at io.github.hligaty.haibaracp.core.SftpPool$KeyedPooledClientFactory.create(SftpPool.java:125)
	at io.github.hligaty.haibaracp.core.SftpPool$KeyedPooledClientFactory.create(SftpPool.java:115)
	at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1073)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:348)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:271)
	at io.github.hligaty.haibaracp.core.SftpPool.borrowObject(SftpPool.java:37)
	at io.github.hligaty.haibaracp.core.SftpTemplate.execute(SftpTemplate.java:87)
	at io.github.hligaty.haibaracp.core.SftpTemplate.list(SftpTemplate.java:236)
```
或者是报错：
```
ownerThread current state is TIMED_WAITING, current stackTrace
	at java.base@11/java.lang.Object.wait(Native Method)
	at java.base@11/java.io.PipedInputStream.read(PipedInputStream.java:326)
	at java.base@11/java.io.PipedInputStream.read(PipedInputStream.java:377)
	at com.jcraft.jsch.ChannelSftp.fill(ChannelSftp.java:2909)
	at com.jcraft.jsch.ChannelSftp.header(ChannelSftp.java:2935)
	at com.jcraft.jsch.ChannelSftp._lstat(ChannelSftp.java:2327)
	at com.jcraft.jsch.ChannelSftp.lstat(ChannelSftp.java:2312)
	at io.github.hligaty.haibaracp.core.SftpClient.test(SftpClient.java:67)
	at io.github.hligaty.haibaracp.core.SftpPool$KeyedPooledClientFactory.validateObject(SftpPool.java:135)
	at io.github.hligaty.haibaracp.core.SftpPool$KeyedPooledClientFactory.validateObject(SftpPool.java:115)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:396)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:271)
	at io.github.hligaty.haibaracp.core.SftpPool.borrowObject(SftpPool.java:37)
	at io.github.hligaty.haibaracp.core.SftpTemplate.execute(SftpTemplate.java:87)
	at io.github.hligaty.haibaracp.core.SftpTemplate.list(SftpTemplate.java:236)
```
上面的日志表明在用主机A进行`borrowObject`已经阻塞了5分钟，这与我们设置的`sftp.pool.max-wait=3000`和`sftp.hosts.A.connectTimeout=3000`又是不匹配的

**Comment by hligaty** [comment]
问题描述 3 中第一段日志没看出什么问题；第二段日志比较明显，可以看出是 Socket 的 InputStream.read 没有超时限制导致一直阻塞，应该可以通过设置 com.jcraft.jsch.Session#setServerAliveInterval 来解决(详见它的内部调用 java.net.Socket#setSoTimeout 上的注释) 解决，但某个操作本身就比较耗时就会出现超时异常。

**Comment by caizy-2020** [comment]
问题描述3中的两段日志都是在连接A主机时的报错，设置`com.jcraft.jsch.Session#setServerAliveInterval `应该只是影响到A主机的连接吧，但我们访问B主机也会出现阻塞，连接B主机时目前并没有出现过这类连接超时的现象

> 问题描述 3 中第一段日志没看出什么问题；第二段日志比较明显，可以看出是 Socket 的 InputStream.read 没有超时限制导致一直阻塞，应该可以通过设置 com.jcraft.jsch.Session#setServerAliveInterval 来解决(详见它的内部调用 java.net.Socket#setSoTimeout 上的注释) 解决，但某个操作本身就比较耗时就会出现超时异常。

**Comment by caizy-2020** [comment]
> 问题描述3中的两段日志都是在连接A主机时的报错，设置`com.jcraft.jsch.Session#setServerAliveInterval `应该只是影响到A主机的连接吧，但我们访问B主机也会出现阻塞，连接B主机时目前并没有出现过这类连接超时的现象
> 
> > 问题描述 3 中第一段日志没看出什么问题；第二段日志比较明显，可以看出是 Socket 的 InputStream.read 没有超时限制导致一直阻塞，应该可以通过设置 com.jcraft.jsch.Session#setServerAliveInterval 来解决(详见它的内部调用 java.net.Socket#setSoTimeout 上的注释) 解决，但某个操作本身就比较耗时就会出现超时异常。

哦，可能是受`sftp.pool.max-active=8`限制导致

**Comment by caizy-2020** [comment]
> 问题描述 3 中第一段日志没看出什么问题；第二段日志比较明显，可以看出是 Socket 的 InputStream.read 没有超时限制导致一直阻塞，应该可以通过设置 com.jcraft.jsch.Session#setServerAliveInterval 来解决(详见它的内部调用 java.net.Socket#setSoTimeout 上的注释) 解决，但某个操作本身就比较耗时就会出现超时异常。

问题还是存在

**修改后的本地的配置：**
SFTP连接池配置：
```
sftp.pool.min-idle-per-key=1
sftp.pool.max-idle-per-key=8
sftp.pool.max-active-per-key=8
sftp.pool.max-active=8
sftp.pool.max-wait=3000
sftp.pool.test-on-borrow=true
sftp.pool.test-on-return=false
sftp.pool.test-while-idle=true
sftp.pool.time-between-eviction-runs=600000
sftp.pool.min-evictable-idle-time-millis=1800000
```
SFTP主机配置：
```
sftp.hosts.A.host=x.x.x.29
sftp.hosts.A.port=22
sftp.hosts.A.username=xx
sftp.hosts.A.password=xx
sftp.hosts.A.connectTimeout=3000
sftp.hosts.A.serverAliveInterval=60000

sftp.hosts.B.host=x.x.x.25
sftp.hosts.B.port=22
sftp.hosts.B.username=xx
sftp.hosts.B.password=xx
sftp.hosts.B.connectTimeout=3000
sftp.hosts.B.serverAliveInterval=60000
```
`serverAliveInterval`参数我们通过重写`io.github.hligaty.haibaracp.core.SftpClient`进行设置
```
session.connect(clientProperties.getConnectTimeout());
session.setServerAliveInterval(clientProperties.getServerAliveInterval());
channelSftp = (ChannelSftp) session.openChannel("sftp");
channelSftp.connect();
```

因为设置了`sftp.pool.max-wait=3000`借取连接时有出现报错，部分日志：
```
io.github.hligaty.haibaracp.core.PoolException: Could not get a resource from the pool; nested exception is java.util.NoSuchElementException: Timeout waiting for idle object
	at io.github.hligaty.haibaracp.core.SftpPool.borrowObject(SftpPool.java:39)
	at io.github.hligaty.haibaracp.core.SftpTemplate.execute(SftpTemplate.java:87)
	at io.github.hligaty.haibaracp.core.SftpTemplate.executeWithoutResultBypermissions(SftpTemplate.java:56)
```

```
Caused by: java.util.NoSuchElementException: Timeout waiting for idle object
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:363)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:271)
	at io.github.hligaty.haibaracp.core.SftpPool.borrowObject(SftpPool.java:37)
	... 132 common frames omitted
```

请问有什么办法可以将当前所有占用连接的对象堆栈信息打印出来吗？想确定到底是不是有些连接一直持有导致连接池无法创建新连接和确定具体是哪些连接占有

**Comment by hligaty** [comment]
打印所有占用的对象比较麻烦，可以考虑打印占用超时的对象：从连接池借出时启动一个定时任务记录堆栈（比如 5 分钟），执行时再打印出来，归还到连接池就取消这个任务

**Comment by caizy-2020** [comment]
通过重写`SftpPool`，`SftpTemplate`，`GenericKeyedObjectPool`加入大量日志后：
1、我们有A，B两个sftp主机，其中A主机会偶发出现创建连接时阻塞的情况，通过增加connectTimeout、serverAliveInterval时长的限制，依旧会出现该问题，定位不到具体原因，暂时只能忽略。
2、当有多个主机时，我们建议的连接池配置：
`sftp.pool.max-wait`不要设置为-1
`sftp.pool.max-active`的值要大于`sftp.pool.max-active-per-key`的值

我们现在B主机被受到影响就是因为sftp.pool.max-active=sftp.pool.max-active-per-key导致，因为A主机阻塞且每个主机的最大连接数与总最大连接数相等，所以当A全部阻塞时会导致其他主机B无法创建连接

**Comment by hligaty** [comment]
> 通过重写`SftpPool`，`SftpTemplate`，`GenericKeyedObjectPool`加入大量日志后： 1、我们有A，B两个sftp主机，其中A主机会偶发出现创建连接时阻塞的情况，通过增加connectTimeout、serverAliveInterval时长的限制，依旧会出现该问题，定位不到具体原因，暂时只能忽略。 2、当有多个主机时，我们建议的连接池配置： `sftp.pool.max-wait`不要设置为-1 `sftp.pool.max-active`的值要大于`sftp.pool.max-active-per-key`的值
> 
> 我们现在B主机被受到影响就是因为sftp.pool.max-active=sftp.pool.max-active-per-key导致，因为A主机阻塞且每个主机的最大连接数与总最大连接数相等，所以当A全部阻塞时会导致其他主机B无法创建连接

像 1.3.1 一样把 GenericKeyedObjectPool 去掉，改成多个 SftpTemplate 的方式会更好些，这样各个连接池就彻底隔离开了

**Comment by hligaty** [comment]
> 通过重写`SftpPool`，`SftpTemplate`，`GenericKeyedObjectPool`加入大量日志后： 1、我们有A，B两个sftp主机，其中A主机会偶发出现创建连接时阻塞的情况，通过增加connectTimeout、serverAliveInterval时长的限制，依旧会出现该问题，定位不到具体原因，暂时只能忽略。 2、当有多个主机时，我们建议的连接池配置： `sftp.pool.max-wait`不要设置为-1 `sftp.pool.max-active`的值要大于`sftp.pool.max-active-per-key`的值
> 
> 我们现在B主机被受到影响就是因为sftp.pool.max-active=sftp.pool.max-active-per-key导致，因为A主机阻塞且每个主机的最大连接数与总最大连接数相等，所以当A全部阻塞时会导致其他主机B无法创建连接

Jsch 还有一处存在超时设置：channelSftp.connect()，可以尝试设置下

**Comment by caizy-2020** [comment]
> **引用的版本：**
> 
> ```
> <dependency>
>     <groupId>io.github.hligaty</groupId>
>     <artifactId>haibaracp-spring-boot-starter</artifactId>
>     <version>1.2.3</version>
> </dependency>
> ```
> 
> **本地的配置：**
> 
> ```
> sftp.pool.min-idle-per-key=1
> sftp.pool.max-idle-per-key=8
> sftp.pool.max-active-per-key=8
> sftp.pool.max-active=8
> sftp.pool.max-wait=-1
> sftp.pool.test-on-borrow=true
> sftp.pool.test-on-return=false
> sftp.pool.test-while-idle=true
> sftp.pool.time-between-eviction-runs=600000
> sftp.pool.min-evictable-idle-time-millis=1800000
> ```
> 
> **问题点：** 1、根据打印出的日志定位到`io.github.hligaty.haibaracp.core.SftpTemplate#execute`方法中的`sftpClient = sftpPool.borrowObject(hostKey);`会偶发的阻塞10几分钟， ![image](https://private-user-images.githubusercontent.com/65394715/284865502-1411a1da-0851-4678-b123-203cc03ea8dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDEwOTMsIm5iZiI6MTcwMjAwMDc5MywicGF0aCI6Ii82NTM5NDcxNS8yODQ4NjU1MDItMTQxMWExZGEtMDg1MS00Njc4LWIxMjMtMjAzY2MwM2VhOGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAxNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNTZhMWQxNmQ5ZTZkODNlOTkxZjNjYTRiZTI2NjNjOTZjN2JiYzU5NjFmMjdlYTU1NzU2OGMzMmQ3ODVlNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0BtuAav1vgyLZnAHHdi_HeViYvi101DxCFnun-Zia-c)
> 
> 阻塞结束后好像会开始执行`org.apache.commons.pool2.impl.GenericKeyedObjectPool#create`方法，因为阻塞结束后打印的是
> 
> ```
> com.jcraft.jsch Connecting to 10.132.4.99 port 12322
> com.jcraft.jsch Connection established
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/65394715/284865966-a8bbc7b3-b525-4bc8-bd28-cc31483caa3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDEwOTMsIm5iZiI6MTcwMjAwMDc5MywicGF0aCI6Ii82NTM5NDcxNS8yODQ4NjU5NjYtYThiYmM3YjMtYjUyNS00YmM4LWJkMjgtY2MzMTQ4M2NhYTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAxNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NjYwNDIwNWRhY2VmMjdmODI4ZjYzZjRhMzg2ZTAwODc3ZWU4NDVkNTVhYjI1Y2VhZTBmYmIxOTgzZGY0YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TLNOTSAFc-ZLfLq6zYEWxOBG15TpkjJZEPUeEiTQDnI)
> 
> 2、本地`SftpTemplate`的代码版本是：https://github.com/hligaty/haibaracp-spring-boot-starter/blob/a9a4c2ea38c5e12dd500040574ec871e3ee5ec9b/src/main/java/io/github/hligaty/haibaracp/core/SftpTemplate.java 3、因为是偶发的，我们也尝试了很久但没有找到复现方式，同时也没有额外的报错日志 4、有初步怀疑过是因为`borrowObject`后未执行`sftpPool.returnObject`或者执行`sftpPool.returnObject`出错才导致`borrowObject`阻塞的，但是我们加入日志后并未发现这一点，因为每次的`borrowObject`都有其对应的`sftpPool.returnObject`立即且成功执行
> 
> **期望：** 1、请问有可能导致该问题的原因有哪些？ 2、我们有什么更进一步的日志打印/方式可帮助获取更精准的错误日志用于排查？ 3、是否可以通过同步最新的`io.github.hligaty.haibaracp.core.SftpTemplate`避免该问题？

**终于，终于找到根本原因了！**

我们自己应用服务器的问题（网络运维层面的，非程序影响）导致。
连接SFTP A主机的应用服务器有WA和WB两台，连接A主机是通过证书的方式，程序`com.jcraft.jsch.KeyPair#load`在WA服务器**加载目录key-path下的证书时会长时间阻塞**，WB无该问题。

这就解释了：
1、为什么连接A主机阻塞是偶发的，因为只有其中的一台服务器有问题
2、为什么我们设置了各种channelSftp.connect()，Session#setServerAliveInterval，connectTimeout等等的**超时限制**都无效，因为**尚未进入连接就已经出现了阻塞**，我们之前的关注重点却一直都在创建连接这一步

**Comment by hligaty** [comment]
> > **引用的版本：**
> > ```
> > <dependency>
> >     <groupId>io.github.hligaty</groupId>
> >     <artifactId>haibaracp-spring-boot-starter</artifactId>
> >     <version>1.2.3</version>
> > </dependency>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **本地的配置：**
> > ```
> > sftp.pool.min-idle-per-key=1
> > sftp.pool.max-idle-per-key=8
> > sftp.pool.max-active-per-key=8
> > sftp.pool.max-active=8
> > sftp.pool.max-wait=-1
> > sftp.pool.test-on-borrow=true
> > sftp.pool.test-on-return=false
> > sftp.pool.test-while-idle=true
> > sftp.pool.time-between-eviction-runs=600000
> > sftp.pool.min-evictable-idle-time-millis=1800000
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **问题点：** 1、根据打印出的日志定位到`io.github.hligaty.haibaracp.core.SftpTemplate#execute`方法中的`sftpClient = sftpPool.borrowObject(hostKey);`会偶发的阻塞10几分钟， ![image](https://private-user-images.githubusercontent.com/65394715/284865502-1411a1da-0851-4678-b123-203cc03ea8dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDEwOTMsIm5iZiI6MTcwMjAwMDc5MywicGF0aCI6Ii82NTM5NDcxNS8yODQ4NjU1MDItMTQxMWExZGEtMDg1MS00Njc4LWIxMjMtMjAzY2MwM2VhOGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAxNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNTZhMWQxNmQ5ZTZkODNlOTkxZjNjYTRiZTI2NjNjOTZjN2JiYzU5NjFmMjdlYTU1NzU2OGMzMmQ3ODVlNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0BtuAav1vgyLZnAHHdi_HeViYvi101DxCFnun-Zia-c)
> > 阻塞结束后好像会开始执行`org.apache.commons.pool2.impl.GenericKeyedObjectPool#create`方法，因为阻塞结束后打印的是
> > ```
> > com.jcraft.jsch Connecting to 10.132.4.99 port 12322
> > com.jcraft.jsch Connection established
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/65394715/284865966-a8bbc7b3-b525-4bc8-bd28-cc31483caa3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDEwOTMsIm5iZiI6MTcwMjAwMDc5MywicGF0aCI6Ii82NTM5NDcxNS8yODQ4NjU5NjYtYThiYmM3YjMtYjUyNS00YmM4LWJkMjgtY2MzMTQ4M2NhYTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAxNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NjYwNDIwNWRhY2VmMjdmODI4ZjYzZjRhMzg2ZTAwODc3ZWU4NDVkNTVhYjI1Y2VhZTBmYmIxOTgzZGY0YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TLNOTSAFc-ZLfLq6zYEWxOBG15TpkjJZEPUeEiTQDnI)
> > 2、本地`SftpTemplate`的代码版本是：https://github.com/hligaty/haibaracp-spring-boot-starter/blob/a9a4c2ea38c5e12dd500040574ec871e3ee5ec9b/src/main/java/io/github/hligaty/haibaracp/core/SftpTemplate.java 3、因为是偶发的，我们也尝试了很久但没有找到复现方式，同时也没有额外的报错日志 4、有初步怀疑过是因为`borrowObject`后未执行`sftpPool.returnObject`或者执行`sftpPool.returnObject`出错才导致`borrowObject`阻塞的，但是我们加入日志后并未发现这一点，因为每次的`borrowObject`都有其对应的`sftpPool.returnObject`立即且成功执行
> > **期望：** 1、请问有可能导致该问题的原因有哪些？ 2、我们有什么更进一步的日志打印/方式可帮助获取更精准的错误日志用于排查？ 3、是否可以通过同步最新的`io.github.hligaty.haibaracp.core.SftpTemplate`避免该问题？
> 
> **终于，终于找到根本原因了！**
> 
> 我们自己应用服务器的问题（网络运维层面的，非程序影响）导致。 连接SFTP A主机的应用服务器有WA和WB两台，连接A主机是通过证书的方式，程序`com.jcraft.jsch.KeyPair#load`在WA服务器**加载目录key-path下的证书时会长时间阻塞**，WB无该问题。
> 
> 这就解释了： 1、为什么连接A主机阻塞是偶发的，因为只有其中的一台服务器有问题 2、为什么我们设置了各种channelSftp.connect()，Session#setServerAliveInterval，connectTimeout等等的**超时限制**都无效，因为**尚未进入连接就已经出现了阻塞**，我们之前的关注重点却一直都在创建连接这一步

👍
